apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exporter-unifi-protect.fullname" . }}
  labels:
    {{- include "exporter-unifi-protect.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "exporter-unifi-protect.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "exporter-unifi-protect.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "exporter-unifi-protect.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.unifi.host.secretName }}
            - name: UNIFI_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.unifi.host.secretName | quote }}
                  key: {{ .Values.unifi.host.secretKey | default "host" | quote }}
            {{- else if .Values.unifi.host.raw}}
            - name: UNIFI_HOST
              value: {{ .Values.unifi.host.raw | quote }}
            {{- end }}
            {{- if .Values.unifi.password.secretName }}
            - name: UNIFI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.unifi.password.secretName | quote }}
                  key: {{ .Values.unifi.password.secretKey | default "password" | quote }}
            {{- else if .Values.unifi.password.raw}}
            - name: UNIFI_PASSWORD
              value: {{ .Values.unifi.password.raw | quote }}
            {{- end }}
            {{- if .Values.unifi.username.secretName }}
            - name: UNIFI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.unifi.username.secretName | quote }}
                  key: {{ .Values.unifi.username.secretKey | default "username" | quote }}
            {{- else if .Values.unifi.username.raw}}
            - name: UNIFI_USERNAME
              value: {{ .Values.unifi.username.raw }}
            {{- end }}
            - name: DEBUG
              value: {{ .Values.debug | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /-/healthy
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
