{{- if and (.Values.metrics.enabled) (.Values.metrics.prometheusRule.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "exporter-unifi-protect.fullname" . }}
  namespace: {{ .Values.metrics.prometheusRule.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "exporter-unifi-protect.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusRule.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ include "exporter-unifi-protect.fullname" . }}
      rules:
      {{- with .Values.metrics.prometheusRule.rules }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
